workflows:
  ios-release-workflow:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Set iOS deployment target to 13.0
        script: |
          echo "Checking Podfile for platform setting..."
          if [ -f ios/Podfile ]; then
            echo "Modifying existing Podfile..."
            sed -i.bak "s/platform :ios, .*/platform :ios, '13.0'/" ios/Podfile
          else
            echo "Creating minimal Podfile with iOS 13.0"
            cat <<EOF > ios/Podfile
platform :ios, '13.0'
use_frameworks!
target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
EOF
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - apenmoh515@g.educaand.es
        notify:
          success: true
          failure: true
