workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean build
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec
          pod cache clean --all
      - name: Get dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS App
        script: flutter build ios --release --no-codesign
      - name: Save build artifact
        script: |
          mkdir -p build/ios/ipa
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa
    artifacts:
      - build/ios/ipa
