workflows:
  ios-workflow:
    name: Build iOS app
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          cd foto_rally
          flutter pub get
      - name: Build iOS app
        script: |
          cd foto_rally
          flutter build ios --release
