// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZDEIj6-8uXDPAo3lZeSgO4fD1tYTPVU',
    appId: '1:247600216562:web:6c85f325bddac55c7a136b',
    messagingSenderId: '247600216562',
    projectId: 'rallyapp-9d657',
    authDomain: 'rallyapp-9d657.firebaseapp.com',
    storageBucket: 'rallyapp-9d657.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDThJbY6YGpauHpmtzQjQ6KQSdK88SAl04',
    appId: '1:247600216562:android:fef1d8637e8ea11e7a136b',
    messagingSenderId: '247600216562',
    projectId: 'rallyapp-9d657',
    storageBucket: 'rallyapp-9d657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_HGEEri_JAZDcM1ddKHMn40A9e5U9Tw',
    appId: '1:247600216562:ios:9f95124944f809077a136b',
    messagingSenderId: '247600216562',
    projectId: 'rallyapp-9d657',
    storageBucket: 'rallyapp-9d657.firebasestorage.app',
    iosBundleId: 'com.example.fotoRally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc_HGEEri_JAZDcM1ddKHMn40A9e5U9Tw',
    appId: '1:247600216562:ios:9f95124944f809077a136b',
    messagingSenderId: '247600216562',
    projectId: 'rallyapp-9d657',
    storageBucket: 'rallyapp-9d657.firebasestorage.app',
    iosBundleId: 'com.example.fotoRally',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhZDEIj6-8uXDPAo3lZeSgO4fD1tYTPVU',
    appId: '1:247600216562:web:7e58765ff65c8bb57a136b',
    messagingSenderId: '247600216562',
    projectId: 'rallyapp-9d657',
    authDomain: 'rallyapp-9d657.firebaseapp.com',
    storageBucket: 'rallyapp-9d657.firebasestorage.app',
  );
}
